version: "3.5"

services:
  build:
    container_name: marlin-build
    image: frealmyr/marlin-build:latest
    user: 1000:1000
    stdin_open: true
    tty: true
    environment:
      - BOARD
      # - USE_LATEST=true # Use latest git tag
      # - USE_REPO=https://github.com/frealmyr/Marlin # USe a different git repo
      # - USE_TAG=2.0.7.1 # Use a specific release tag
      # - USE_BRANCH=bugfix-2.0.x # Use a branch instead of latest tag
      # - FW_EXTENSION=hex
    volumes:
      - $MARLIN_FIRMWARE:/home/platformio/build
      - $MARLIN_CONFIGURATION:/home/platformio/CustomConfiguration
      # - ./build-marlin.sh:/home/platformio/build-marlin.sh # Use build script in repo instead of image
